import type { TranslationLang } from './settings';
import { createPersistedStore } from './store';

export interface SurahMeta {
  n: number;
  ar: string;
  tr: string; // transliterated name
  en: string; // English meaning
  type: 'meccan' | 'medinan';
  ayahs: number;
}

export interface Verse {
  n: number;
  ar: string;
  translation?: string;
  translit?: string;
}

// Static data generated by scripts/build-quran-data.mjs (Uthmani text from QuranEnc,
// translations via Tanzil.net / QuranEnc). Never edited by hand.
const BASE = `${import.meta.env.BASE_URL}data/quran`;

const jsonCache = new Map<string, Promise<unknown>>();

function getJSON<T>(url: string): Promise<T> {
  let p = jsonCache.get(url);
  if (!p) {
    p = fetch(url).then((r) => {
      if (!r.ok) throw new Error(`Failed to load ${url} (${r.status})`);
      return r.json();
    });
    p.catch(() => jsonCache.delete(url)); // allow retry after a failure
    jsonCache.set(url, p);
  }
  return p as Promise<T>;
}

export const loadSurahList = () => getJSON<SurahMeta[]>(`${BASE}/surahs.json`);

export async function loadSurah(
  n: number,
  opts: { translation: TranslationLang; transliteration: boolean },
): Promise<Verse[]> {
  const [ar, tr, tl] = await Promise.all([
    getJSON<string[]>(`${BASE}/ar/${n}.json`),
    opts.translation !== 'none' ? getJSON<string[]>(`${BASE}/${opts.translation}/${n}.json`) : null,
    opts.transliteration ? getJSON<string[]>(`${BASE}/translit/${n}.json`) : null,
  ]);
  return ar.map((text, i) => ({ n: i + 1, ar: text, translation: tr?.[i], translit: tl?.[i] }));
}

export const loadTranslation = (lang: Exclude<TranslationLang, 'none'>, n: number) =>
  getJSON<string[]>(`${BASE}/${lang}/${n}.json`);

export interface Excerpt {
  surah: string;
  ar: string[];
  tl: string[];
  en: string[];
}
export const loadExcerpts = () => getJSON<Record<string, Excerpt>>(`${BASE}/excerpts.json`);

/** Opening verse of each Juz (standard Tanzil division). */
export const JUZ_STARTS: [number, number][] = [
  [1, 1], [2, 142], [2, 253], [3, 93], [4, 24], [4, 148], [5, 82], [6, 111], [7, 88], [8, 41],
  [9, 93], [11, 6], [12, 53], [15, 1], [17, 1], [18, 75], [21, 1], [23, 1], [25, 21], [27, 56],
  [29, 46], [33, 31], [36, 28], [39, 32], [41, 47], [46, 1], [51, 31], [58, 1], [67, 1], [78, 1],
];

export interface Range {
  surah: number;
  from: number;
  to: number;
}

/** The surah/verse ranges that make up Juz `j` (1-30). */
export function juzRanges(j: number, surahs: SurahMeta[]): Range[] {
  const [s0, a0] = JUZ_STARTS[j - 1];
  const end = JUZ_STARTS[j]; // undefined for Juz 30
  const ranges: Range[] = [];
  for (let s = s0; s <= 114; s++) {
    const from = s === s0 ? a0 : 1;
    let to = surahs[s - 1].ayahs;
    if (end) {
      if (s > end[0] || (s === end[0] && end[1] === 1)) break;
      if (s === end[0]) to = end[1] - 1;
    }
    ranges.push({ surah: s, from, to });
  }
  return ranges;
}

export function juzOf(surah: number, ayah: number): number {
  for (let j = JUZ_STARTS.length - 1; j >= 0; j--) {
    const [s, a] = JUZ_STARTS[j];
    if (surah > s || (surah === s && ayah >= a)) return j + 1;
  }
  return 1;
}

export interface VerseRef {
  surah: number;
  ayah: number;
  at: number; // timestamp
  name?: string; // surah name, for display
}

export const lastReadStore = createPersistedStore<VerseRef | null>('quran.lastRead', null);
export const bookmarksStore = createPersistedStore<VerseRef[]>('quran.bookmarks', []);

export function toggleBookmark(surah: number, ayah: number): boolean {
  const list = bookmarksStore.get();
  const exists = list.some((b) => b.surah === surah && b.ayah === ayah);
  bookmarksStore.set(
    exists ? list.filter((b) => !(b.surah === surah && b.ayah === ayah)) : [{ surah, ayah, at: Date.now() }, ...list],
  );
  return !exists;
}

/** Folds names like "Al-Baqarah" / "al baqara" / "Baqarah" so they match each other. */
export function foldName(s: string): string {
  return s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/^(al|an|ar|as|at|ad|ash|az)[-\s]/, '')
    .replace(/[^a-z0-9]/g, '')
    .replace(/h$/, '');
}

/** Parses "2:255", "2 255", "2" into a reference. */
export function parseRef(q: string, surahs: SurahMeta[]): { surah: number; ayah?: number } | null {
  const m = q.trim().match(/^(\d{1,3})(?:\s*[:.\s]\s*(\d{1,3}))?$/);
  if (!m) return null;
  const surah = Number(m[1]);
  if (surah < 1 || surah > 114) return null;
  const ayah = m[2] ? Number(m[2]) : undefined;
  if (ayah != null && (ayah < 1 || ayah > surahs[surah - 1].ayahs)) return null;
  return { surah, ayah };
}

/**
 * The Uthmani text (KFGQPC Hafs encoding) writes the open, staggered tanween —
 * which marks ikhfa/idgham — with code points that the King Fahd font draws
 * specially but standard fonts do not. For display we map them to the standard
 * Unicode open-tanween characters (U+08F0–08F2). No letter or mark is added or
 * removed; the stored data stays byte-identical to the source.
 */
const OPEN_TANWEEN: Record<string, string> = {
  'ٗ': 'ࣰ', // open fathatan
  'ٞ': 'ࣱ', // open dammatan
  'ٖ': 'ࣲ', // open kasratan
};

export function displayArabic(text: string): string {
  return text.replace(/[ٖٗٞ]/g, (c) => OPEN_TANWEEN[c]);
}
